version: "3"
services:
  billing-service:
    image: billing-service.jar
    container_name: billing-container
    ports:
      - "8083:8080"
    depends_on:
      - customer-service
      - eureka-discovery
  customer-service:
    image: customer-service.jar
    container_name: customer-container
    ports:
      - "8082:8080"
    depends_on:
      - eureka-discovery
  eureka-discovery:
    image: eureka-discovery-service.jar
    container_name: eureka-container
    ports:
      - "8761:8080"
  gateway:
    image: gateway.jar
    container_name: gateway-container
    ports:
      - "8040:8080"
    depends_on:
      - customer-service
      - billing-service
      - eureka-discovery
